[toolchain]
channel = "1.89.0"
components = ["rust-src", "rust-analyzer", "clippy"]
targets = [
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]
profile = "default"
